<a href="https://colab.research.google.com/github/j-claudinei-f/j-claudinei-f/blob/main/BaseDual.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Álgebra Linear: Base dual e base ortogonal em $\mathbb{R}^n$ para resolução de sistema lineares**

José Claudinei Ferreira

Universidade Federal de Alfenas

#**Base dual em $\mathbb{R}^n$ para resolução de sistema lineares**

Considere a $$A=\begin{bmatrix}1&1&1&1&1\\1&-1&1&1&-1\\1&1&-1&-1&1\\1&1&3&3&1\end{bmatrix}.$$

Essa matriz representa um transformação linear $T:U\to W$, em relação a alguma base do domínio e e alguma base do contradomínio. Considerando essas bases, podemos ver essa transformação $T$ como uma função, com domínio $\mathbb{R}^5$ e contradomínio $\mathbb{R}^4$.

Dois subespaços vetoriais importantes relacionados a $T$, ou à matriz $A$, são o núcleo $Nuc(T)$ e a imagem $Im(T)$.



Colocamos então dois problemas:

a) Determine uma base para $Nuc(T)$;

b) Determine uma base para $Im(T)$ e verifique se os vetores $v=(-1,1,-3,3)$ e $w=(2,2,-2,-2)$ estão na imagem de $T$.

**Uma solução:**

Vamos usar eliminação de Gauss para resolver os dois itens.

b) Por eliminação da matriz extendida do sistema, colocando $v$ e $w$, na sexta e sétima coluna, vemos que os sistemas lineares $Ax=v$ e $Ax=w$ são impossíveis, ou seja, esses vetores não estão na imagem de $T$.

In [ ]:
import numpy as np, pandas as pd
A1=np.array([[1,1,1,1,1,-1,2],[1,-1,1,1,-1,1,2],[1,1,-1,-1,1,-3,-2],[1,1,3,3,1,3,-2]]) #
dt=pd.DataFrame(A1,columns=["c_1", "c2", "c3", "c4", "c5",'v','w'],index=['l1', 'l2', 'l3', 'l4']) # Matriz A extedida para resolver também o item b)
display(dt)

c_1  c2  c3  c4  c5  v  w
l1    1   1   1   1   1 -1  2
l2    1  -1   1   1  -1  1  2
l3    1   1  -1  -1   1 -3 -2
l4    1   1   3   3   1  3 -2

O processo de eliniação é feito com calcularora abaixo.

In [ ]:
import copy
A=copy.deepcopy(A1)
A[1]=-(A[1]-A[0])/2
A[2]=-(A[2]-A[0])/2
A[3]=(A[3]-A[0])/2
A[3]=A[3]-A[2]

dt=pd.DataFrame(A,columns=["c_1'", "c2'", "c3'", "c4'", "c5'","v'","w'"],index=["l1'", "l2'", "l3'", "l4'"]) # Matriz A extedida para resolver também o item b)
display(dt)

c_1'  c2'  c3'  c4'  c5'  v'  w'
l1'     1    1    1    1    1  -1   2
l2'     0    1    0    0    1  -1   0
l3'     0    0    1    1    0   1   2
l4'     0    0    0    0    0   1  -4

**Obs:** Da matriz escalonada vemos:

1. Vemos que a linha $(1,1,3,3,1)$ da matriz $A$ é combinação linear das três linhas anteriores. Vemos também que o conjunto $\{(1,1,1,1,1),(1,-1,1,1,-1),(1,1,-1,-1,1)\}$ com as três primeiras linhas de $A$ é LI. Então o espaço linha de $A$ tem dimensão 3.

2. Vemos que as colunas $c_3$ e $c_5$ de $A$ são combinações lineares das três colunas anteriores. Vemos ainda que o conjunto $\{c_1,c_2,c_3\}=\{(1,1,1,1),(1,-1,1,1),(1,1,-1,3)\}$ com as três primeiras colunas de $A$ é LI. Então o espaço coluna de $A$, que é a imagem $Im(T)$ de $T$ (numa base), tem dimensão 3.

3. Como o domínio de $T$ tem dimensão 5. Devemos ter que o núcleo $Nuc(T)$ terá dimensão $5-3=2$.

b) Na forma escalanda, o sistema $Ax=v$ e $Ax=w$ tomam as formas $$\begin{bmatrix}1& 1& 1& 1& 1\\ 0& 1& 0& 0& 1\\0& 0& 1& 1& 0\\0& 0& 0& 0& 0\end{bmatrix}\begin{bmatrix}x_1\\x_2\\x_3\\x_4\\x_5\end{bmatrix}=\begin{bmatrix}-1\\-1\\1\\1\end{bmatrix},\qquad \begin{bmatrix}1& 1& 1& 1& 1\\ 0& 1& 0& 0& 1\\0& 0& 1& 1& 0\\0& 0& 0& 0& 0\end{bmatrix}\begin{bmatrix}x_1\\x_2\\x_3\\x_4\\x_5\end{bmatrix}=\begin{bmatrix}2\\0\\2\\-4\end{bmatrix}$$

Os sistemas $Ax=v$ e $Ax=w$ são impossíveis porque a última linha dos sistemas, na forma escalonada, leva às igualdades $0=1=-4$, o que não é aceito no problema.


---

a) Para o núcleo de $T$, queremos os vetores $x \in \mathbb{R}^5$ tais que $Ax = 0$ ou
$$\begin{bmatrix}1& 1& 1& 1& 1\\ 0& 1& 0& 0& 1\\0& 0& 1& 1& 0\\0& 0& 0& 0& 0\end{bmatrix}\begin{bmatrix}x_1\\x_2\\x_3\\x_4\\x_5\end{bmatrix}=\begin{bmatrix}0\\0\\0\\0\end{bmatrix}$$ A solução geral do sistema homogêneo é: \begin{cases}x_2&=&-x_5\\x_3&=&-x_4\\x_1&=&-(x_2+x_5)-(x_3+x_4)=0\end{cases}
que pode ser escrito como
$$
x = s \begin{bmatrix} 0 \\ -1 \\ 0 \\ 0 \\ 1\end{bmatrix} + t \begin{bmatrix} 0 \\ 0 \\ -1 \\ 1 \\ 0 \end{bmatrix}, \quad s, t \in \mathbb{R}
$$

Uma base de $\ker(T)$ é:
  $$
  \left\{
  \begin{bmatrix} 0 \\ -1 \\ 0 \\ 0 \\ 1\end{bmatrix},
  \begin{bmatrix} 0 \\ 0 \\ -1 \\ 1 \\ 0 \end{bmatrix}
  \right\}
  $$
- Um vetor não nulo no núcleo é:
  $$
  u = \begin{bmatrix} 0\\ -1 \\ -1 \\ 1 \\ 1\end{bmatrix}\in \ker(T).
  $$

---

**Obs:** O sistema linear $Ax=v$ não tem solução **porque $T$ não é sobrejetiva**. Nesse caso, **$T$ não é injetiva** também. Mesmo assim, vamos manipular um pouco o problema para uma matriz que se comporta quase como uma inversa à direita de $A$.

Primeiro observe que as três primeira linhas da matriz $A$ são linearmente independentes e geram um subspaço de $\mathbb{R}^5$. Por outro lado $ker(T)$ é também um subespaço de $\mathbb{R}^5$ e somando os elementos dos dois subespaços obtemos o espaço todo.

Seja $B$ a matriz que contenha as três primeiras linhas iguais à de $A$ e as duas últimas iguais aos elementos da base de $kert(T)$ que encontramos acima, ou seja, cujas linhas formam uma base de $\mathbb{R}^5$.

In [ ]:
# Define os vetores u1, u2, u3
u1 = np.array([1, 1, 1, 1, 1])
u2 = np.array([1, -1, 1, 1, -1])
u3 = np.array([1, 1, -1, -1, 1])
B=[u1,u2,u3,[0,-1,0,0,1],[0,0,-1,1,0]]
B

[array([1, 1, 1, 1, 1]),
 array([ 1, -1,  1,  1, -1]),
 array([ 1,  1, -1, -1,  1]),
 [0, -1, 0, 0, 1],
 [0, 0, -1, 1, 0]]

Seja $B_i$ a inversa de $B$.

In [ ]:
Bi=np.linalg.inv(B) # np.linalg.inv() calcula matriz inversa.
Bi

array([[ 0.  ,  0.5 ,  0.5 ,  0.  ,  0.  ],
       [ 0.25, -0.25, -0.  , -0.5 , -0.  ],
       [ 0.25, -0.  , -0.25, -0.  , -0.5 ],
       [ 0.25,  0.  , -0.25,  0.  ,  0.5 ],
       [ 0.25, -0.25,  0.  ,  0.5 ,  0.  ]])

Desta forma, quando tivermos uma equação da forma $Au=b$, podemos escrever $y=Bu$ ou $u=B_iy$ e escrever o sistema de forma equivalente como $$AB_iy=b.$$

Nesse caso particular do item b), incluímos mais uma coordenada nula em $v$ e $b=(-1,1,-3,3,0)$. Temos que:

O sistema $AB_iy=b$ toma a forma
$$\begin{bmatrix}1.& 0.& 0.&  0.&0.\\    0.&  1.&  0.&  0.&  0\\ 0.& 0.& 1.&  0.&  0.\\ 2.&  0.&-1.&  0.&  0.\\0&0&0&0&0\end{bmatrix}\begin{bmatrix}y_1\\y_2\\y_3\\y_4\\y_5\end{bmatrix}=\begin{bmatrix}-1\\1\\-3\\3\\0\end{bmatrix},$$

ou seja, $B_i$ atua como uma quase inversa de $A$, e trocamos o sistema $Ax=b$ por um sistema já escalonado.

Segue $y_4$ e $y_5$ são de livre escolha e que $y_1=-1$, $y_2=1$, $y_3=-3$ e <font color=red> $3=2y_1-y_3=-2+3=1$, o que não é aceito nesse problema.

In [ ]:
b=np.array([-1,1,-3,3,0])

In [ ]:
A2=A1[0:4,0:5].tolist() # A1 é a matriz A com v e w incluídos como colunas.
A2.append([0,0,0,0,0])  # Foram retiradas as colunas v e w e incluída uma lina nula no final.
A2=np.array(A2)
A2

array([[ 1,  1,  1,  1,  1],
       [ 1, -1,  1,  1, -1],
       [ 1,  1, -1, -1,  1],
       [ 1,  1,  3,  3,  1],
       [ 0,  0,  0,  0,  0]])

In [ ]:
A2@Bi  # Cálculo de AB_i

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 0.,  1.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.],
       [ 2.,  0., -1.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.]])

**Obs:** Embora o sistema não tenha solução, o que poderíamos ter descobrido por elimninação. Esssa forma de resolver nos diz que os vetores da forma $$u=B_i\begin{bmatrix}-1\\1\\-3\\w_4\\w_5\end{bmatrix}$$ são quase soluções do sistema. O erro que cometemos é $$AB_i\begin{bmatrix}-1\\1\\-3\\w_4\\w_5\end{bmatrix}-\begin{bmatrix}-1\\1\\-3\\3\\0\end{bmatrix}=\begin{bmatrix}-1\\1\\-3\\1\\0\end{bmatrix}-\begin{bmatrix}-1\\1\\-3\\3\\0\end{bmatrix}=\begin{bmatrix}0\\0\\0\\-2\\0\end{bmatrix}$$

Tomando $w_4=w_5=0$ temos um candidato$$u_1=B_i\begin{bmatrix}-1\\1\\-3\\w_4\\w_5\end{bmatrix}=\begin{bmatrix}-1. \\ -0.5\\  0.5\\  0.5\\-0.5\end{bmatrix}.$$


In [ ]:
u1=Bi@np.array([-1,1,-3,0,0])
u1,A2@u1,A2@u1-b

(array([-1. , -0.5,  0.5,  0.5, -0.5]),
 array([-1.,  1., -3.,  1.,  0.]),
 array([ 0.,  0.,  0., -2.,  0.]))

Tomando $w_4=7,\,w_5=8$ temos um candidato$$u_2=B_i\begin{bmatrix}-1\\1\\-3\\w_4\\w_5\end{bmatrix}=\begin{bmatrix}-1. \\ -4. \\ -3.5\\  4.5\\  3.\end{bmatrix}.$$

In [ ]:
u2=Bi@np.array([-1,1,-3,7,8])
u2,A2@u2,A2@u2-b

(array([-1. , -4. , -3.5,  4.5,  3. ]),
 array([-1.,  1., -3.,  1.,  0.]),
 array([ 0.,  0.,  0., -2.,  0.]))

A diferença $u_1-u_2$ é um elemento do núcleo de $T$.

Qual vetor da forma $$B_i\begin{bmatrix}-1\\1\\-3\\w_4\\w_5\end{bmatrix}$$ tem o menor módulo?

Para responder isso vamos para a seção seguinte...