<a href="https://colab.research.google.com/github/j-claudinei-f/j-claudinei-f/blob/main/C%C3%B3pia_de_Revis%C3%A3oGA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Álgebra Linear: Introdução - Revisão**

José Claudinei Ferreira

Universidade Federal de Alfenas

#**Um problema para pensarmos:**

Sejam $u=(1,3,5)$, $v=(1,2,3)$, $w=(1,4,5)$ e $k=(1,1,1)$.
Resolva o sistema linear $$\alpha u+\beta v+\gamma w=k.$$

Vejamos por eliminação se o conjunto $\{u,v,w\}$ é mesmo L.I. Vamos escrever a matriz $M$, cujas linhas são $u$, $v$ e $w$:
$$M=\begin{bmatrix}1&3&5\\1&2&3\\1&4&5\end{bmatrix}.$$

In [ ]:
import numpy as np    # Pacote para usar Álgebra Linear

u,v,w=np.array([1,3,5]), np.array([1,2,3]), np.array([1,4,5])
M=np.array([u,v,w])

M

array([[1, 3, 5],
       [1, 2, 3],
       [1, 4, 5]])

Subtraindo $u$ de $v$ e de $w$ temos a matriz $M_1$:

In [ ]:
M1=np.array([u,v-u,w-u])

print('M1 é obtido escalonado primeira coluna de M','\n M1=', M1)

M1 é obtido escalonado primeira coluna de M 
 M1= [[ 1  3  5]
 [ 0 -1 -2]
 [ 0  1  0]]


 <font color=green> Ou seja, $$\begin{cases}v-u=(0, -1, -2)\qquad \text{Linha 2 menos linha 1}\\\\w-u=(0,1,0)\qquad \text{Linha 3 menos linha 1}\\\\(w-u)+(v-u)=w+v-2u=(0,0,-2)\qquad \text{Linha 3 mais linha 2}\end{cases}\tag{Eliminação}$$

 <font color=blue> Em particular, temos que $$w=2u-v+(0,0,-2).$$

Isso já nos dá a matriz M escalonada com $$\begin{bmatrix}1&3&5\\0&-1&-2\\0&0&2\end{bmatrix}$$



**Obs:** Note que $$u-\frac{1}{2}v-\frac{1}{2}w=(0,0,1)$$ e que $$u-3(0,1,0)-5(0,0,1)=u-3(w-u)-5(u-\frac{1}{2}v-\frac{1}{2}w)=-u+\frac{5}{2}v-\frac{1}{2}w=(1,0,0)$$ que $w$ não pode ser escrito como soma das duas primeiras.

Nesse processo de escrever \begin{cases}-u+\frac{5}{2}v-\frac{1}{2}w&=&(1,0,0)\\w-u&=&(0,1,0)\\u-\frac{1}{2}v-\frac{1}{2}w&=&(0,0,1)\end{cases} estamos calculando a matriz inversa de $$M=\begin{bmatrix}1& 3& 5\\1&2& 3\\1& 4& 5\end{bmatrix},$$ cujas linhas são os vetores $u$, $v$ e $w$, que é $$M^{-1}=\begin{bmatrix}-1&\frac{5}{2}&\frac{-1}{2}\\-1&0&1\\1&\frac{-1}{2}&\frac{-1}{2}\end{bmatrix}.$$

Isso porque, por exemplo, podemos escrever $-u+\frac{5}{2}v-\frac{1}{2}w=(1,0,0)$ na forma matricial como:

$$\begin{bmatrix}-1&\frac{5}{2}&-\frac{1}{2}\end{bmatrix}\begin{bmatrix}1& 3& 5\\1&2& 3\\1& 4& 5\end{bmatrix}=\begin{bmatrix}1&0&0\end{bmatrix}.$$

In [ ]:
np.linalg.inv(M)

array([[-1. ,  2.5, -0.5],
       [-1. , -0. ,  1. ],
       [ 1. , -0.5, -0.5]])

Seguindo esse raciocínio, podemos escrever a expressão da Eliminação de Gauss, como:

$$\begin{bmatrix}1&0&0\\-1&1&0\\-1&0&1\end{bmatrix}\begin{bmatrix}1& 3& 5\\1&2& 3\\1& 4& 5\end{bmatrix}=\begin{bmatrix}1& 3& 5\\0&-1&-2\\0&1&0\end{bmatrix},$$ para descrever o processo de escalonar na primeira coluna:

<font color=green> $$\begin{cases}v-u=(0, -1, -2)\qquad \text{Linha 2 menos linha 1}\\\\w-u=(0,1,0)\qquad \text{Linha 3 menos linha 1}\end{cases}\tag{Eliminação inicial}.$$

A segunda parte da eliminação, dada por <font color=green> $$(w-u)+(v-u)=w+v-2u=(0,0,-2)\Longrightarrow  u-\frac{1}{2}v-\frac{1}{2}w=(0,0,1)\qquad \text{Linha 3 mais linha 2}$$

pode ser escrita na forma matricial como:

$$\begin{bmatrix}1&0&0\\0&1&0\\0&1&1\end{bmatrix}\begin{bmatrix}1&0&0\\-1&1&0\\-1&0&1\end{bmatrix}\begin{bmatrix}1& 3& 5\\1&2& 3\\1& 4& 5\end{bmatrix}=\begin{bmatrix}1&0&0\\0&1&0\\0&1&1\end{bmatrix}\begin{bmatrix}1& 3& 5\\0&-1&-2\\0&1&0\end{bmatrix}=\begin{bmatrix}1& 3& 5\\0&-1&-2\\0&0&-2\end{bmatrix},$$ para descrever o processo de escalonar na primeira e na segunda coluna.

Denotando por $$U=\begin{bmatrix}1& 3& 5\\0&-1&-2\\0&0&-2\end{bmatrix}$$ e
 $$L^{-1}=\begin{bmatrix}1&0&0\\0&1&0\\0&1&1\end{bmatrix}\begin{bmatrix}1&0&0\\-1&1&0\\-1&0&1\end{bmatrix}=\begin{bmatrix}1&0&0\\-1&1&0\\-2&1&1\end{bmatrix}$$ temos que $M=LU$, para $$L=\begin{bmatrix}1&0&0\\1&1&0\\2&-1&1\end{bmatrix}.$$


In [ ]:
L1=np.array([[1,0,0],[-1,1,0],[-1,0,1]])

L1,L1@M

(array([[ 1,  0,  0],
        [-1,  1,  0],
        [-1,  0,  1]]),
 array([[ 1,  3,  5],
        [ 0, -1, -2],
        [ 0,  1,  0]]))

In [ ]:
L2=np.array([[1,0,0],[0,1,0],[0,1,1]])
Li=L2@L1
U=Li@M
L2,Li,U

(array([[1, 0, 0],
        [0, 1, 0],
        [0, 1, 1]]),
 array([[ 1,  0,  0],
        [-1,  1,  0],
        [-2,  1,  1]]),
 array([[ 1,  3,  5],
        [ 0, -1, -2],
        [ 0,  0, -2]]))

In [ ]:
L=np.linalg.inv(Li)
L,L@U

(array([[ 1., -0., -0.],
        [ 1.,  1.,  0.],
        [ 1., -1.,  1.]]),
 array([[1., 3., 5.],
        [1., 2., 3.],
        [1., 4., 5.]]))

Por fim, nosso problema inicial $$\alpha u+\beta v+\gamma w=k$$ toma a forma matricial $$\begin{bmatrix}\alpha &\beta &\gamma\end{bmatrix}M=k$$ ou $$\begin{bmatrix}\alpha &\beta &\gamma\end{bmatrix}=kM^{-1}=\begin{bmatrix}1&1&1\end{bmatrix}\begin{bmatrix}-1&\frac{5}{2}&\frac{-1}{2}\\-1&0&1\\1&\frac{-1}{2}&\frac{-1}{2}\end{bmatrix}=\begin{bmatrix}-1&2&0\end{bmatrix}.$$

In [ ]:
-u+2*v

array([1, 1, 1])

#**Sobre núcleo de matriz, espaço linha e espaço coluna**

Considere os vetores $u_1=(1,2,2)$, $u_2=(2,5,4)$, $u_3=(1,3,2)$, $u_4=(2,7,4)$ e $u_5=(1,1,0)$.

Considere agora a matriz $$A=\begin{bmatrix}1 &2& 2\\2& 5& 4\\1& 3& 2\\2& 7& 4\\1& 1& 0\end{bmatrix}\approx \begin{bmatrix} 1 & 2 & 2\\
  0&  1 & 0\\ 0 & 1 & 0\\ 0 & 3 & 0\\ 0 &-1 &-2\end{bmatrix}\approx \begin{bmatrix} 1 & 2&  2\\ 0 & 1&  0\\ 0 & 0 & 0\\ 0 & 0 & 0\\ 0 & 0 &-2\end{bmatrix},$$ aqui $\approx $ denota o processo de escalonamento ou eliminação de Gauss.

a) Determine uma base para o espaço $W$, gerado pelo conjunto $\mathcal{A}=\{u_1,\,u_2,\,u_3,\,u_4,\,u_5\}$, que é o espaço linha de $A$.

b) Determine o núcleo de $A$.

**a) Uma solução:**

Usando o processo de eliminação nas linhas de $A$. Obtemos:
\begin{cases}u_2'&=&u_2-2u_1\\u_3'&=& u_3-u_1\\u_4'&=&u_4-2u_1\\u_5'&=&u_5-u_1\end{cases} Depois \begin{cases}0&=&u_3'-u_2'\\0&=& u_4'-3u_2'\\u_5''&=&u_5'+u_2'\end{cases} O que nos dá \begin{cases}u_3'=u_2'&=&u_2-2u_1\\u_4'=3u_2'&=&3u_2-6u_1\\u_5''&=&u_5-3u_1+u_2\end{cases}

Segue que $\mathcal{B}=\{u_1,\,u_2,\,u_5\}$ é uma base para o espaço $W$.

**b) Uma solução:** O núcleo de $A$ é o conjunto $$N(A)=\left\{\alpha=\begin{bmatrix}\alpha_1\\\alpha_2\\\alpha_3\end{bmatrix}\in \mathbb{R}^3\big | A\alpha=\begin{bmatrix}1 &2& 2\\2& 5& 4\\1& 3& 2\\2& 7& 4\\1& 1& 0\end{bmatrix}\begin{bmatrix}\alpha_1\\\alpha_2\\\alpha_3\end{bmatrix}=\begin{bmatrix}0\\0\\0\\0\\0\end{bmatrix}\right\}.$$ Usando a forma escalonada de $A$ obtemos que $A\alpha=0$ apenas quando $\alpha=0$ Então $N(A)=\{(0,0,0)\}$.

**Alguns cálculos a seguir:**

In [ ]:
import numpy as np
u1=np.array([1,2,2])
u2=np.array([2,5,4])
u3=np.array([1,3,2])
u4=np.array([2,7,4])
u5=np.array([1,1,0])

A=np.array([u1,u2,u3,u4,u5])
print('A=\n',A)


A=
 [[1 2 2]
 [2 5 4]
 [1 3 2]
 [2 7 4]
 [1 1 0]]


In [ ]:
A[1]=A[1]-2*A[0]
A[2]=A[2]-A[0]
A[3]=A[3]-2*A[0]
A[4]=A[4]-A[0]
print('A=\n',A)

A=
 [[ 1  2  2]
 [ 0  1  0]
 [ 0  1  0]
 [ 0  3  0]
 [ 0 -1 -2]]


In [ ]:
A[2]=A[2]-A[1]
A[3]=A[3]-3*A[1]
A[4]=A[4]+A[1]
print('A=\n',A)

A=
 [[ 1  2  2]
 [ 0  1  0]
 [ 0  0  0]
 [ 0  0  0]
 [ 0  0 -2]]


O processo de eliminação pode ser reescrito como
pode ser escrita na forma matricial como:

$$\begin{bmatrix}1&0&0&0&0\\0&1&0&0&0\\0&-1&1&0&0\\0&-3&0&1&0\\0&1&0&0&1\end{bmatrix}\begin{bmatrix}1&0&0&0&0\\-2&1&0&0&0\\-1&0&1&0&0\\-2&0&0&1&0\\-1&0&0&0&1\end{bmatrix}\begin{bmatrix}1 &2& 2\\2& 5& 4\\1& 3& 2\\2& 7& 4\\1& 1& 0\end{bmatrix}=\begin{bmatrix}1&0&0&0&0\\0&1&0&0&0\\0&-1&1&0&0\\0&-3&0&1&0\\0&1&0&0&1\end{bmatrix} \begin{bmatrix} 1 & 2 & 2\\
  0&  1 & 0\\ 0 & 1 & 0\\ 0 & 3 & 0\\ 0 &-1 &-2\end{bmatrix}= \begin{bmatrix} 1 & 2&  2\\ 0 & 1&  0\\ 0 & 0 & 0\\ 0 & 0 & 0\\ 0 & 0 &-2\end{bmatrix}.$$

Denotando por $$L^{-1}=L_2L_1\Longrightarrow L=L_1^{-1}L_2^{-1},$$ $$L_2=\begin{bmatrix}1&0&0&0&0\\0&1&0&0&0\\0&-1&1&0&0\\0&-3&0&1&0\\0&1&0&0&1\end{bmatrix},$$ $$L_1=\begin{bmatrix}1&0&0&0&0\\-2&1&0&0&0\\-1&0&1&0&0\\-2&0&0&1&0\\-1&0&0&0&1\end{bmatrix}$$ e $$U= \begin{bmatrix} 1 & 2&  2\\ 0 & 1&  0\\ 0 & 0 & 0\\ 0 & 0 & 0\\ 0 & 0 &-2\end{bmatrix},$$ temos que $$A=LU.$$

In [ ]:
U=np.array([[1,2,2],[0,1,0],[0,0,0],[0,0,0],[0,0,-2]])
U

array([[ 1,  2,  2],
       [ 0,  1,  0],
       [ 0,  0,  0],
       [ 0,  0,  0],
       [ 0,  0, -2]])

In [ ]:
L1=  np.array([[1,0,0,0,0],[-2,1,0,0,0],[-1,0,1,0,0],[-2,0,0,1,0],[-1,0,0,0,1]])
L1

array([[ 1,  0,  0,  0,  0],
       [-2,  1,  0,  0,  0],
       [-1,  0,  1,  0,  0],
       [-2,  0,  0,  1,  0],
       [-1,  0,  0,  0,  1]])

In [ ]:
L2 = np.array([[1, 0, 0, 0, 0],
              [0, 1, 0, 0, 0],
              [0, -1, 1, 0, 0],
              [0, -3, 0, 1, 0],
              [0, 1, 0, 0, 1]])
L2


array([[ 1,  0,  0,  0,  0],
       [ 0,  1,  0,  0,  0],
       [ 0, -1,  1,  0,  0],
       [ 0, -3,  0,  1,  0],
       [ 0,  1,  0,  0,  1]])

In [ ]:
L=np.linalg.inv(L1)@np.linalg.inv(L2)
L

array([[ 1.,  0.,  0.,  0.,  0.],
       [ 2.,  1.,  0.,  0.,  0.],
       [ 1.,  1.,  1.,  0.,  0.],
       [ 2.,  3.,  0.,  1.,  0.],
       [ 1., -1.,  0.,  0.,  1.]])

In [ ]:
L@U

array([[1., 2., 2.],
       [2., 5., 4.],
       [1., 3., 2.],
       [2., 7., 4.],
       [1., 1., 0.]])

#**Para treinar:**

Usem a calculadora aqui do Colab para resolver os exercícios 1, 2 e 3 da Seção 3.6 do [livro do Lion](chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://docs.ufpr.br/~higidio/Ensino/Books/Leon%28Algebra%20linear%29.pdf).