<a href="https://colab.research.google.com/github/j-claudinei-f/j-claudinei-f/blob/main/Recorr%C3%AAncias.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Relacões de recorrência e problemas de contagem**

José Claudinei Ferreira

Universidade Federal de Alfenas

#**Exemplo 1: Progressão aritmética de ordem 2**

Sejam $x_1,\,x_2,\,\ldots,\,x_n$ as alturas de $n$ pessoas.

a) Mostre que $2n-3$ comparações entre dois números são suficientes para determinar a pessoa (ou as pessoas) mais baixa e a mais alta.

b) Suponha que os valores os valores $x_i$ ainda não foram ordenados e que queira formar uma fila com essas $n$ pessoas, considerando a mais baixa na frente da mais alta e algum acordo no caso de pessoas com a mesma altura. Você pode escolher a primeira e a última da fila e depois inserir as demais pessoas entre elas, se houver mais de 2 pessoas. Para isso, você pode encontrar a mais baixa e a mais alta das $n-2$ pessoas restantes e inseri-las na fila, entre as que já estavam lá ...

Seja $a_n$ uma quantidade de comparações suficiente para ordenar as $n$ pessoas por ordem de altura. Determine uma relação de recorrência para $a_n$.

c) Mostre que $$a_n=\frac{n(n-1)}{2}$$ comparações entre alturas são suficientes para ordenar a fila com $n$ pessoas, por ordem de altura, de acordo com a sugestão do item 2).

**Solução**

a) Isso pode ser feito por indução finita e já foi feito em aula.

b) Usando o item a) podemos usar os seguintes passos para ordenar as $n$ pessoas na fila:

1. Se $n=1$ não é preciso fazer comparações e $a_1=0$. Se $n=2$ compare a altura de uma pessoa com a da outra e terá $a_2=1$ comparações.

2. Se já sabe o valor de $a_j$, para $1\leq j< n$, usando o item a) temos que é possível determinar uma pessoa mais alta e uma mais baixa das $n$ pessoas, fazendo $2n-3$ comparações entre as alturas delas. Vão restar $n-2$ delas, que você pode ordenar com $a_{n-2}$ comparações entre as alturas delas. Segue que

$$\begin{cases}a_n&=&a_{n-2}+2n-3\\
a_1&=&0\\
a_2&=&1&\end{cases}$$

é uma relação de recorrência que dá um número suficiente de comparações para ordenar as $n$ pessoas (E vimos em outra questão que existe forma muito melhor para fazer isso!).

c) Podemos demonstrar isso por indução, usando a relação de recorrência do item b).

Mas vamos resolver a relação de recorrência do item b), em vez disso.

Antes veja alguns valores de $a_n$, a partir da relação de recorrência obtida.

In [5]:
a=[0,1]
for i in range(2,20):
  a.append(a[-2]+2*(i+1)-3)
print(a)

[0, 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, 66, 78, 91, 105, 120, 136, 153, 171, 190]


Agora vamos definir outra relação de recorrência como
$b_n=a_n-a_{n-1}$. Podemos obter alguns valores para $b_n$:

In [6]:
b=[]
for i in range(1,len(a)-1):
  b.append(a[i]-a[i-1])
print(b)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18]


Usando a recorrência de $a_n$, temos que
$$\begin{cases}b_n&=&a_n-a_{n-1}&=&(a_{n-2}+2n-3)-(a_{n-3}+2(n-2)-3)&=&a_{n-2}-a_{n-3}+4=b_{n-2}+4\\
b_2&=&1\\
b_3&=&2&\end{cases}$$

Definimos outra recorrência como $c_n=b_n-b_{n-1}$:

In [7]:
c=[]
for i in range(1,len(b)-1):
  c.append(b[i]-b[i-1])
print(c)

[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]


Usando a recorrência de $b_n$, temos que
$$\begin{cases}c_n&=&b_n-b_{n-1}&=&(b_{n-2}+4)-(b_{n-3}+4)&=&b_{n-2}-b_{n-3}=c_{n-2}\\
c_3&=&1\\
c_4&=&1&\end{cases}$$

**Obs. 1:** Note que  $$\sum_{j\leq n}c_j=(b_n-b_{n-1})+(b_{n-1}-b_{n-2}+\cdots +(b_3-b_2)=b_n-b_2 $$ e que  $$\sum_{j\leq n}b_j=(a_n-a_{n-1})+(a_{n-1}-a_{n-2}+\cdots +(a_2-a_1)=a_n-a_1. $$

Seque que $c_n=1$, para todo $n\geq 3$, serve, o que implica que $$\begin{cases} b_n&=&b_{n-1}+1\\b_2&=&1\end{cases},$$ que é uma P.A. de razão $1$, ou que $b_n=n-1.$ Por fim, temos que $$\begin{cases}a_n&=&a_{n-1}+(n-1)\\a_1&=&0\end{cases}$$ é uma soma de uma PA de razão $1$.

Então, $$a_n=\frac{n(n-1)}{2}=\frac{(b_2+b_n)(n-1)}{2}$$

**Observação 2:** Ao analisar um problema de contagem por meio de relações de recorrência, é possível obter diferentes fórmulas que descrevem a mesma quantidade.

Por exemplo, no item (b):

1. Se você começasse escolhendo uma pessoa qualquer, dentre as $ n $ disponíveis, não seriam necessárias comparações — ou seja, $ a_1 = 0 $. Se em seguida escolhesse uma segunda pessoa, dentre as \( n-1 \) restantes, e a comparasse com a primeira, faria uma única comparação, resultando em $ a_2 = 1 $. Assim, uma fila com duas pessoas estaria ordenada.

1. Já com uma fila ordenada de $ n-1 $ pessoas, ao inserir a $ n $-ésima pessoa, você poderia compará-la com cada uma das outras $ n-1$ para encontrar sua posição correta. Isso exige $ n-1 $ comparações adicionais.

Essa estratégia gera a seguinte relação de recorrência:


\begin{cases}
a_n = a_{n-1} + (n-1) \\
a_1 = 0
\end{cases}

que também conduz à fórmula fechada:
$$
a_n = \frac{n(n-1)}{2}.
$$


**Obs. 3:** Obtida a expressão para $a_n$, podemos definir outra relação de recorrência como \begin{cases}d_n&=&d_{n-1}+\frac{n(n-1)}{2}\\d_1&=&0\end{cases} que é a soma de $a_i$, para $1\leq i\leq n$.

Como $a_n$ é um polinômio de grau $2$ esperamos que $d_n$ seja um polinômio de grau $3$, ou seja, supomos que $$d_n=a+bn+cn^2+dn^3$$ e procuramos determinar $a, b,c, d$.

In [8]:
d=[]
for i in range(1,10):
  if i==1:
    d.append(0)
  else:
    d.append(d[-1]+i*(i-1)/2)
d

[0, 1.0, 4.0, 10.0, 20.0, 35.0, 56.0, 84.0, 120.0]

Então, temos o sistema linear \begin{cases}a+&b+&c+&d&=d_1=0\\a+&2b+&2^2c+&2^3d&=d_2=1\\a+&3b+&3^2c+&3^3d&=d_3=4\\a+&4b+&4^2c+&4^3d&=d_4=10\end{cases}

In [13]:
n=4
M=[[j**i for i in range(n)] for j in range(1,n+1)]
M
import numpy as np # para lidar com sistemas lineares.
M=np.array(M)
print('M=',M)
b=np.array([d[0],d[1],d[2],d[3]]) # O contador de índices comça no 0.

sol=np.linalg.solve(M,b)
sol,M@sol

M= [[ 1  1  1  1]
 [ 1  2  4  8]
 [ 1  3  9 27]
 [ 1  4 16 64]]


(array([ 7.49400542e-16, -1.66666667e-01,  8.88178420e-16,  1.66666667e-01]),
 array([ 0.,  1.,  4., 10.]))

Temos que $a=0$, $b=-\frac{1}{6}$, $c=0$ e $d=\frac{1}{6}$.

Assim, $$d_n=-\frac{1}{6}n+\frac{1}{6}n^3.$$

Teste:

In [16]:
dd=[]
for i in range(1,10):
    dd.append((-i+i**3)/6 )
dd

[0.0, 1.0, 4.0, 10.0, 20.0, 35.0, 56.0, 84.0, 120.0]

#**Exemplo 2: Contando desordenações**

Seja $(x_1,\,x_2,\,\ldots,\,x_n)$ uma lista com $n$ coisas distintas. De quantas formas podemos reordenar essa lista, de tal forma que cada elemento mude de posição?



**Solução:** Permutação Caótica (Desarranjo)

Uma permutação caótica, ou desarranjo, é uma permutação dos $n$ elementos em que nenhum elemento permanece na sua posição original.

A quantidade de deranjos de $n$ elementos é denotada por $D_n$, e satisfaz a seguinte relação de recorrência:

\begin{cases}
D_n &=& (n - 1)(D_{n-1} + D_{n-2})\\
D_0&=&1\\
D_1&=&0
\end{cases}


**Explicação da recorrência:**

A ideia é considerar o que acontece com o primeiro elemento. Ele não pode ir para a posição 1 (por definição de deranjo), então ele tem $n-1$ escolhas. Duas situações ocorrem a partir disso:

1. Se ele troca com alguém que também vai para a posição 1 (uma "troca direta"), o problema se reduz a  $D_{n-2}$.

2. Se ele vai para uma posição arbitrária e o elemento dessa posição não vai para 1, o problema se reduz a $D_{n-1}$.

**Resolvendo a recorrênca:**

Note que

$$c_n=D_n-nD_{n-1}=(n - 1)(D_{n-1} + D_{n-2})-nD_{n-1}=(n - 1)D_{n-2}-nD_{n-1}-D_{n-1}=-c_{n-1}.$$

In [2]:
D=[]
for i in range(10):
  if i==0:
    D.append(1)
  elif i==1:
    D.append(0)
  else:
    D.append((i-1)*(D[-1]+D[-2]))
D

[1, 0, 1, 2, 9, 44, 265, 1854, 14833, 133496]

In [3]:
c=[]
for i in range(1,10):
  c.append(D[i]-i*D[i-1])
c

[-1, 1, -1, 1, -1, 1, -1, 1, -1]

O que nos diz que $c_n=(-1)^{n}$ e segue que
\begin{cases}D_n&=&nD_{n-1}+(-1)^{n}\\
D_1&=&0\end{cases}

Seja $a_n=na_{n-1}$. Então podemos verificar que $a_n=n!$ é o número total de listas formadas pelos $n$ elementos $x_i$.

Tomando agora $$D_n=a_ny_n=n!y_n,$$
temos que $y_1=0$ e $$D_n=n!y_n=nD_{n-1}+(-1)^n=n(n-1)!y_{n-1}+(-1)^n.$$ Isso nos dá
$$y_n=y_{n-1}+\frac{(-1)^n}{n!}.$$

Então, \begin{cases}y_2&=&y_1+\frac{(-1)^2}{2!}\\\\y_3&=&y_1+\frac{(-1)^2}{2!}+\frac{(-1)^3}{3!}\\\vdots \\ y_n&=&y_1+\frac{(-1)^2}{2!}+\frac{(-1)^3}{3!}+\cdots+\frac{(-1)^n}{n!}\end{cases} e $$D_n=n!\left(\frac{(-1)^0}{0!}+\frac{(-1)^1}{1!}+\frac{(-1)^2}{2!}+\frac{(-1)^3}{3!}+\cdots+\frac{(-1)^n}{n!}\right).$$

A fórmula explícita para $D_n$:

$$
D_n = n! \sum_{k=0}^{n} \frac{(-1)^k}{k!}
$$

Esta fórmula pode ser aproximada por:

$$
D_n \approx \frac{n!}{e}.
$$