<a href="https://colab.research.google.com/github/j-claudinei-f/j-claudinei-f/blob/main/SomasPolinomiais.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Matemática Discreta**

José Claudinei Ferreira

Universidade Federal de Alfenas

#**Somas polinômiais e somas exponenciais**

[Link](https://colab.research.google.com/drive/1bLRvrx2v6SSbGuS_I3vzfnQ5wBsWg_I8?usp=sharing) para página anterior, sobre relações de recorrência lineares.

As somas polinômiais $$s(n)=\sum_{k=1}^n p(k),$$ em que $$p(k)=\sum_{j=0}^m\alpha_jk^j$$ é um polinômio de grau $m$, podem ser escritas como $$s(n+1)=s(n)+p(n+1),$$ e são relações de recorrência lineares. 

**Exemplo 6:** 

Para o caso em que  relação de recorrência é $$s(n+1)=s(n)+3((n+1)^2+n+2),\quad s(1)=12,$$ já vimos que  $$s(n)=n^3+3n^2+5n+3,$$ na questão sobre divibilidade de $s(n)$ por $3$. Veja o [Exemplo 2](https://colab.research.google.com/drive/1bLRvrx2v6SSbGuS_I3vzfnQ5wBsWg_I8#scrollTo=9bvZPMuG2xNi).

In [ ]:
def s(n):
  return n**3+3*n**2+5*n+3


for i in range(1,10+1):
  print(i,s(i))

1 12
2 33
3 72
4 135
5 228
6 357
7 528
8 747
9 1020
10 1353


Nesse caso, na relação de recorrência aparece o polinômio $$p(n+1)=3((n+1)^2+n+2),$$ ou $$p(n)=3(n^2+n+1).$$ e vamos denotar por $$a(n)=\sum_{k=1}^n p(k),$$ para compararmos com $s(n)$.

In [ ]:
def a(n):
  p=0
  for k in range(1,n+1):
    p=p+3*(k**2+k+1)
  return p

for i in range(1,10+1):
  print(i,a(i))

1 9
2 30
3 69
4 132
5 225
6 354
7 525
8 744
9 1017
10 1350


Parece que $s(n)=a(n)+3$, o que nos daria $$a(n)=n^3+3n^2+5n=s(n)-3.$$ Observe que $$p(1)=9=s_1-3.$$ Vamos ver que esse é o caso, olhando para o exemplo que segue.

**Obs:** 

As somas $$s(n)=s_1+\sum_{k=1}^n f(k),$$ em que $s_1$ é conhecido e $f(k)$ é uma função conhecida, também podem ser escritas como $$s(n+1)=s(n)+f(n+1),$$ e são relações de recorrência lineares. Veja o exemplo anterior. 

Entretanto, as somas polinomiais são mais fáceis de serem escritas de forma mais simples. 

**Exemplo 7:**

Tirando da mente Exemplo 6, para o caso em que a relação de recorrência é $$s(n+1)=s(n)+3((n+1)^2+n+2),\quad s(1)=1,\tag{1}$$ devemos ter $$p(n+1)=3((n+1)^2+n+2)$$ ou $$p(n)=3(n^2+n+1)$$

Usando a recorrência, temos que 
$$s_2=s_1+p(2),\qquad s_3=s_2+p(3)=s_1+p(2)+p(3),\ldots,$$ ou que sugere que
$$s(n)=s_1-p(1)+\sum_{k=1}^n3(k^2+k+1),\tag{2}$$ o que sugere que 
$$s(n)=\alpha n^3+\beta n^2+\delta n+\gamma\tag{3}$$ é um polinômio de grau 3.

Vamos testar as exepressões $(1)$ e $(2)$ no que segue:

In [ ]:
def s(n):   # Expressão (1)
  if (n==1):
    p=1
  else: 
    p=s(n-1)+3*(n**2+n+1)  
  return p

for i in range(1,10+1):
  print(i,s(i))

1 1
2 22
3 61
4 124
5 217
6 346
7 517
8 736
9 1009
10 1342


Vemos a igualdade entre as expresões $(1)$ e $(2)$ para $s_n$.

In [ ]:
def sf(n):  # Expressão 2.
  p=1 - 9      # s_1-p(1)
  for k in range(1,n+1):
      p=p+3*(k**2+k+1)
  return p

for i in range(1,10+1):
  print(i,sf(i))

1 1
2 22
3 61
4 124
5 217
6 346
7 517
8 736
9 1009
10 1342


Para buscarmos a expressão $(3)$ é preciso procurar $\alpha$, $\beta$, $\delta$ e $\gamma$, tais que 
$$\begin{cases}s(1)&=&\alpha 1^3+\beta 1^2+\delta 1+\gamma=1\\
s(2)&=&\alpha 2^3+\beta 2^2+\delta 2+\gamma=22\\
s(2)&=&\alpha 3^3+\beta 3^2+\delta 3+\gamma=61\\
s(2)&=&\alpha 4^3+\beta 4^2+\delta 4+\gamma=124.\end{cases}.$$

Isso é um sistema linear, da forma matricial $$\begin{bmatrix}1&  1&  1&  1\\ 8 & 4&  2 & 1\\27 & 9 & 3 & 1\\64& 16 & 4  &1\end{bmatrix}u=\begin{bmatrix}1\\22\\61\\124\end{bmatrix},$$ que podemos resolver por escalonamento ou eliminação de Gauss. Mas aqui uso a calculadora do Python.

In [ ]:
import numpy as np

A=np.array([[1,1,1,1],[2**3,2**2,2,1],[3**3,3**2,3,1],[4**3,4**2,4,1]])

v=np.array([1,22,61,124])
print(A,v)

[[ 1  1  1  1]
 [ 8  4  2  1]
 [27  9  3  1]
 [64 16  4  1]] [  1  22  61 124]


In [ ]:
u=np.linalg.solve(A,v)
u

array([ 1.,  3.,  5., -8.])

Obtemos $\alpha=1$, $\beta=3$, $\delta=5$ e $\gamma=-8$, como já era esperado (usando agora o Exemplo 6).

In [ ]:
def sg(n):
  p=n**3+3*n**2+5*n-8
  return p

for i in range(1,10+1):
  print(i,sg(i))

1 1
2 22
3 61
4 124
5 217
6 346
7 517
8 736
9 1009
10 1342


**Teorema:** Dada a  relação de recorrência $$s(n+1)=s(n)+f(n+1),\tag{1}$$ para algum $s_1$ escolhido.

Segue que
$$s_2=s_1+f(2),\qquad s_3=s_2+f(3)=s_1+f(2)+f(3),\ldots,$$ ou que sugere que
$$s(n)=s_1-f(1)+\sum_{k=1}^nf(k),\tag{2}.$$ 


<font color=blue> a) Se $f(n)$ for polinômio de grau $m$, em $n$. Então
$$s(n)=\sum_{i=0}^{m+1}\alpha_in^i=g(n)\tag{3}$$ é um polinômio de grau $m+1$, em $n$, que pode ser determinado por meio da resolução de um sistema linear de equações.

<font color=blue> b) Se $f(n)=c\times r^{n-1}$ para algum número real $r\neq 1$ e $c$ fixos. Então
$$s(n)=s_1+c\sum_{i=0}^{n-1}r^i\tag{4}=s_1+c\frac{r^n-1}{r-1}=g(n).$$ 


**Exemplo 8:** Um exemplo do item b) do Teorema é a [Questão 5 do ENQ 2023/1](https://profmat-sbm.org.br/wp-content/uploads/sites/4/sites/4/2023/03/ENQ-20231-Gabarito-com-Pautas.pdf).

**Obs:** [Link](https://colab.research.google.com/drive/1gK8Ifc2sh_QBqZgBz1Volnk0Vryk7nYO?usp=sharing) para a parte não presencial da Avaliação I.

#**Próximo passo:** 

Resolver as relações de recorrência da forma $$s_{n+1}=g(n)s_n+f(n)$$ e $$a_{n+1}=ba_n+ca_{n-1}.$$